# Generated by Django 4.2.7 on 2026-04-10 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('department', models.CharField(choices=[('Management', 'Management'), ('Whole Plant', 'Whole Plant'), ('Administrator/ERP', 'Administrator/ERP'), ('Security', 'Security'), ('HR & Admin', 'HR & Admin'), ('HSEF', 'HSEF'), ('Mechanical (Crushing & Pyro)', 'Mechanical (Crushing & Pyro)'), ('Mechanical (Packing & Utility & Grinding)', 'Mechanical (Packing & Utility & Grinding)'), ('Electrical', 'Electrical'), ('Instrument', 'Instrument'), ('Process & Production', 'Process & Production'), ('QC', 'QC'), ('Civil', 'Civil'), ('IT', 'IT'), ('Purchase', 'Purchase'), ('Logistics', 'Logistics'), ('Store', 'Store'), ('Automobile', 'Automobile'), ('Account', 'Account'), ('Sales Account', 'Sales Account'), ('Sales', 'Sales'), ('Marketing', 'Marketing')], max_length=100)),
                ('direction', models.CharField(choices=[('outgoing', 'Outgoing (Out of Factory)'), ('incoming', 'Incoming (Into Factory)')], default='outgoing', max_length=20)),
                ('is_returnable', models.BooleanField(default=False, verbose_name='Returnable Material')),
                ('copy_type', models.CharField(blank=True, choices=[('original', 'Original for Buyer'), ('duplicate', 'Duplicate for Transporter'), ('triplicate', 'Triplicate for Supplier')], default='original', max_length=20, verbose_name='Document Copy')),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=30)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=200)),
                ('lr_number', models.CharField(blank=True, default='', max_length=100, verbose_name='LR No.')),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('courier', 'Courier'), ('hand', 'By Hand'), ('other', 'Other')], default='road', max_length=20)),
                ('pass_date', models.DateField()),
                ('pass_time', models.TimeField()),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Expected Return Date')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason for Dispatch')),
                ('remarks', models.TextField(blank=True, default='')),
                ('consignor_name', models.CharField(default='PMC CEMENT LTD.', max_length=200)),
                ('consignor_address', models.TextField(default='Village Nandni, Tehsil Sihora, Dist. Jabalpur (M.P.) - 483225')),
                ('consignor_contact', models.CharField(blank=True, default='', max_length=50)),
                ('consignor_state', models.CharField(default='Madhya Pradesh', max_length=100)),
                ('consignor_state_code', models.CharField(default='23', max_length=10)),
                ('consignor_pan', models.CharField(default='AABCP1234A', max_length=20)),
                ('consignor_gstin', models.CharField(default='23AABCP1234A1Z5', max_length=20, verbose_name='Consignor GSTIN')),
                ('party_name', models.CharField(default='', max_length=200, verbose_name='Consignee / Party Name')),
                ('party_address', models.TextField(default='', verbose_name='Consignee Full Address')),
                ('city', models.CharField(default='', max_length=100)),
                ('party_contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('party_contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('party_state', models.CharField(blank=True, default='', max_length=100)),
                ('party_pan', models.CharField(blank=True, default='', max_length=20, verbose_name='Consignee PAN')),
                ('party_gstin', models.CharField(blank=True, default='', max_length=20, verbose_name='Consignee GSTIN')),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='CGST %')),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='SGST %')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_material_passes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Gate Pass',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Particulars')),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20, verbose_name='HSN Code')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='', max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='material_pass.materialgatepass')),
            ],
            options={
                'verbose_name': 'Material Item',
            },
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mgp_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='material_pass.materialgatepass')),
            ],
            options={
                'verbose_name': 'Material Attachment',
            },
        ),
    ]
