# Generated by Django 4.2.7 on 2026-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_pass', '0002_challan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgatepass',
            name='bank_account_number',
            field=models.CharField(blank=True, default='1234567890', max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='materialgatepass',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='SBIN0001234', max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='materialgatepass',
            name='bank_name',
            field=models.CharField(blank=True, default='State Bank of India', max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='materialgatepass',
            name='consignor_office_address',
            field=models.TextField(blank=True, default='Plot No. 12, Industrial Area, Jabalpur (M.P.) - 482001', verbose_name='Office Address'),
        ),
    ]
