# Generated by Django 4.2.7 on 2026-04-10 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material_pass', '0003_alter_materialgatepass_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('department', models.CharField(choices=[('Management', 'Management'), ('Whole Plant', 'Whole Plant'), ('Administrator/ERP', 'Administrator/ERP'), ('Security', 'Security'), ('HR & Admin', 'HR & Admin'), ('HSEF', 'HSEF'), ('Mechanical (Crushing & Pyro)', 'Mechanical (Crushing & Pyro)'), ('Mechanical (Packing & Utility & Grinding)', 'Mechanical (Packing & Utility & Grinding)'), ('Electrical', 'Electrical'), ('Instrument', 'Instrument'), ('Process & Production', 'Process & Production'), ('QC', 'QC'), ('Civil', 'Civil'), ('IT', 'IT'), ('Purchase', 'Purchase'), ('Logistics', 'Logistics'), ('Store', 'Store'), ('Automobile', 'Automobile'), ('Account', 'Account'), ('Sales Account', 'Sales Account'), ('Sales', 'Sales'), ('Marketing', 'Marketing')], max_length=100)),
                ('is_returnable', models.BooleanField(default=False, verbose_name='Returnable Material')),
                ('request_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Required By Date')),
                ('reason', models.TextField(verbose_name='Reason / Purpose')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved by Store'), ('converted', 'Converted to Gate Pass'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Item Description')),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='', max_length=30)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='material_pass.materialrequest')),
            ],
            options={
                'verbose_name': 'Material Request Item',
            },
        ),
        migrations.AddField(
            model_name='materialgatepass',
            name='request_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='material_pass.materialrequest', verbose_name='Material Request'),
        ),
    ]
