# Generated by Django 4.2.7 on 2026-04-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_pass', '0004_material_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material Gate Pass Request'},
        ),
        migrations.AlterModelOptions(
            name='materialrequestitem',
            options={'verbose_name': 'Material Gate Pass Request Item'},
        ),
        migrations.AddField(
            model_name='materialgatepass',
            name='gst_rate',
            field=models.CharField(choices=[('0.00', '0% — Exempt / Nil'), ('0.10', '0.1% — Special (e.g. certain food items)'), ('0.25', '0.25% — Rough diamonds'), ('1.50', '1.5% — Cut & polished diamonds / precious stones'), ('3.00', '3% — Gold, Silver, Jewellery'), ('5.00', '5% — Essential goods (food, transport, etc.)'), ('12.00', '12% — Standard goods (processed food, etc.)'), ('18.00', '18% — Standard goods (most goods & services)'), ('28.00', '28% — Luxury / demerit goods (cement, cars, etc.)')], default='18.00', max_length=6, verbose_name='GST Rate %'),
        ),
        migrations.AddField(
            model_name='materialgatepass',
            name='gst_type',
            field=models.CharField(choices=[('cgst_sgst', 'CGST + SGST (Intra-State)'), ('igst', 'IGST (Inter-State)'), ('none', 'Exempt / Nil Rated')], default='cgst_sgst', max_length=20, verbose_name='GST Type'),
        ),
    ]
