# Generated by Django 4.2.7 on 2026-04-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material_pass', '0005_gst_type_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='hod_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='hod_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='hod_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='hod_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='store_hod_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — Pending HOD Approval'), ('hod_approved', 'HOD Approved — Pending Store HOD'), ('hod_rejected', 'Rejected by HOD'), ('store_approved', 'Approved by Store HOD'), ('store_rejected', 'Rejected by Store HOD'), ('converted', 'Converted to Gate Pass')], default='draft', max_length=20),
        ),
    ]
