# Generated by Django 4.2.7 on 2026-04-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Security', 'Security'), ('Admin', 'Administration'), ('Production', 'Production'), ('Quality', 'Quality Control'), ('Logistics', 'Logistics'), ('Other', 'Other')], max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_plain', models.CharField(blank=True, max_length=128)),
                ('can_access_dashboard', models.BooleanField(default=True)),
                ('can_access_accounts', models.BooleanField(default=False)),
                ('can_access_internal_pass', models.BooleanField(default=True)),
                ('can_access_visitor_pass', models.BooleanField(default=True)),
                ('can_approve_internal_pass', models.BooleanField(default=False)),
                ('can_approve_visitor_pass', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reporting_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ['employee_name'],
            },
        ),
    ]
