# Generated by Django 4.2.7 on 2026-04-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_helpdesk_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('management', 'Management'), ('president_plant_head', 'President-Plant Head'), ('department_hod', 'Department HOD'), ('hr', 'HR'), ('security', 'Security'), ('employee', 'Employee')], max_length=30, unique=True)),
                ('show_igp', models.BooleanField(default=True, verbose_name='Show IGP')),
                ('show_vgp', models.BooleanField(default=True, verbose_name='Show VGP')),
                ('show_hd', models.BooleanField(default=True, verbose_name='Show Help Desk')),
            ],
            options={
                'verbose_name': 'Role Module Access',
            },
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='maintenance_message',
            field=models.TextField(blank=True, default='The Software is under maintenance. If you have any query kindly contact the ERP Department.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
