# Generated by Django 4.2.7 on 2026-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_smtp_maintenance_rolemoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='perm_reports_audit',
            field=models.BooleanField(default=False, verbose_name='Audit Log View'),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_reports_igp',
            field=models.BooleanField(default=False, verbose_name='IGP Reports View'),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_reports_vgp',
            field=models.BooleanField(default=False, verbose_name='VGP Reports View'),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_reports_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_reports_igp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_reports_vgp',
            field=models.BooleanField(default=False),
        ),
    ]
