# Generated by Django 4.2.7 on 2026-04-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_reports_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='tkt_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Ticket Next Number'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tkt_prefix',
            field=models.CharField(default='TKT', max_length=10, verbose_name='Ticket Prefix'),
        ),
    ]
