# Generated by Django 4.2.7 on 2026-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_systemsetting_tkt_next_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='perm_mgp_approve',
            field=models.BooleanField(default=False, verbose_name='MGP Approve/Reject'),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_mgp_delete',
            field=models.BooleanField(default=False, verbose_name='MGP Delete'),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_mgp_export',
            field=models.BooleanField(default=False, verbose_name='MGP Export Reports'),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_mgp_view',
            field=models.BooleanField(default=True, verbose_name='MGP View'),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_mgp_write',
            field=models.BooleanField(default=True, verbose_name='MGP Write'),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_mgp_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_mgp_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_mgp_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_mgp_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_mgp_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mgp_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='MGP Next Number'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mgp_prefix',
            field=models.CharField(default='MGP', max_length=10, verbose_name='Material Pass Prefix'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('otp_verified', 'OTP Verified'), ('session_timeout', 'Session Timeout'), ('duplicate_kick', 'Duplicate Session Kicked'), ('igp_create', 'IGP Created'), ('igp_approve', 'IGP Approved'), ('igp_reject', 'IGP Rejected'), ('igp_return', 'IGP Returned'), ('vgp_create', 'VGP Created'), ('vgp_approve', 'VGP Approved'), ('vgp_reject', 'VGP Rejected'), ('vgp_checkout', 'VGP Checked Out'), ('employee_create', 'Employee Created'), ('employee_edit', 'Employee Edited'), ('employee_delete', 'Employee Deleted'), ('settings_change', 'Settings Changed'), ('password_reset', 'Password Reset'), ('page_view', 'Page View'), ('mgp_create', 'MGP Created'), ('mgp_approve', 'MGP Approved'), ('mgp_reject', 'MGP Rejected'), ('mgp_return', 'MGP Returned')], max_length=30),
        ),
    ]
