# Generated by Django 4.2.7 on 2026-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_employee_perm_mgp_approve_employee_perm_mgp_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='mr_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='MR Next Number'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mr_prefix',
            field=models.CharField(default='MR', max_length=10, verbose_name='Material Request Prefix'),
        ),
    ]
