# Generated by Django 4.2.7 on 2026-04-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_notificationpermission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationpermission',
            name='unique_notification_permission',
        ),
        migrations.AlterUniqueTogether(
            name='notificationpermission',
            unique_together={('scope', 'role', 'employee', 'department', 'notification_type')},
        ),
    ]
