# Generated by Django 4.2.7 on 2026-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_workflow_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationworkflow',
            name='pass_type',
            field=models.CharField(choices=[('igp', 'Internal Gate Pass (IGP)'), ('vgp', 'Visitor Gate Pass (VGP)'), ('mgp', 'Material Gate Pass (MGP)'), ('helpdesk', 'IT Help Desk')], max_length=20),
        ),
    ]
