# Generated by Django 4.2.7 on 2026-04-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('purpose', models.CharField(choices=[('official', 'Official Work'), ('personal', 'Personal Work'), ('medical', 'Medical Emergency'), ('bank', 'Bank Work'), ('government', 'Government Work'), ('other', 'Other')], max_length=50)),
                ('purpose_detail', models.TextField()),
                ('destination', models.CharField(max_length=200)),
                ('out_date', models.DateField()),
                ('out_time', models.TimeField()),
                ('expected_return_time', models.TimeField()),
                ('transport_mode', models.CharField(choices=[('own_vehicle', 'Own Vehicle'), ('company_vehicle', 'Company Vehicle'), ('public_transport', 'Public Transport'), ('on_foot', 'On Foot')], max_length=30)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('approval_remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('actual_return_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_internal_passes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Gate Pass',
                'ordering': ['-created_at'],
            },
        ),
    ]
