# Generated by Django 4.2.7 on 2026-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_pass', '0003_gatepassapproval_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalgatepass',
            name='destination',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
    ]
