# Generated by Django 4.2.7 on 2026-04-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_company', models.CharField(blank=True, max_length=200)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('id_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('other', 'Other')], max_length=30)),
                ('id_number', models.CharField(max_length=50)),
                ('no_of_visitors', models.PositiveIntegerField(default=1)),
                ('visit_purpose', models.CharField(choices=[('business_meeting', 'Business Meeting'), ('vendor', 'Vendor/Supplier'), ('interview', 'Interview'), ('audit', 'Audit/Inspection'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance/Repair'), ('industry_visit', 'Industry Visit'), ('other', 'Other')], max_length=50)),
                ('visit_detail', models.TextField()),
                ('visit_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('expected_out_time', models.TimeField()),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('items_carried', models.TextField(blank=True, help_text='List items brought by visitor')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_out', 'Checked Out')], default='pending', max_length=20)),
                ('approval_remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('actual_out_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitor_passes', to=settings.AUTH_USER_MODEL)),
                ('person_to_meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Gate Pass',
                'ordering': ['-created_at'],
            },
        ),
    ]
