# Generated by Django 4.2.7 on 2026-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_pass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgatepass',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
