# Generated by Django 4.2.7 on 2026-04-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor_pass', '0002_visitorgatepass_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgatepass',
            name='access_card_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Access Card No.'),
        ),
        migrations.AddField(
            model_name='visitorgatepass',
            name='material',
            field=models.CharField(blank=True, max_length=200, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='visitorgatepass',
            name='material_category',
            field=models.CharField(blank=True, choices=[('returnable', 'Returnable'), ('non_returnable', 'Non-Returnable')], max_length=20, verbose_name='Material Category'),
        ),
        migrations.AddField(
            model_name='visitorgatepass',
            name='visitor_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='expected_out_time',
            field=models.TimeField(verbose_name='Out Time'),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='in_time',
            field=models.TimeField(verbose_name='In Time'),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='items_carried',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='person_to_meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to=settings.AUTH_USER_MODEL, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='visit_purpose',
            field=models.CharField(choices=[('business_meeting', 'Business Meeting'), ('vendor', 'Vendor/Supplier'), ('interview', 'Interview'), ('audit', 'Audit/Inspection'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance/Repair'), ('industry_visit', 'Industry Visit'), ('other', 'Other')], max_length=50, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='visitor_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='visitorgatepass',
            name='visitor_phone',
            field=models.CharField(max_length=15, verbose_name='Visitor Mobile Number'),
        ),
    ]
