# Generated by Django 4.2.7 on 2026-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_pass', '0003_visitorgatepass_access_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorgatepass',
            name='visitor_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
    ]
